project_name: goreleaser-test
builds:
  - main: build/goreleaser/stub.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: goreleaser-test
    ignore:
      - goos: windows
        goarch: arm64
    hooks:
      post:
        - ./.goreleaser-hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: goreleaser-test
    repository:
      owner: pamburus
      name: homebrew-tap-test
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: true
    url_template: "https://github.com/pamburus/goreleaser-test/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Pavel Ivanov
      email: mr.pavel.ivanov@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/pamburus/goreleaser-test"
    description: "Test project for using GoReleaser with rust"
    license: "MIT"
    skip_upload: auto
    custom_block: |
      head "https://github.com/pamburus/goreleaser-test.git"
    test: |
      system "#{bin}/goreleaser-test"
    install: |
      system "cargo", "install", *std_cargo_args
